### ISSUE TITLE
Limited multi server support (based on WLAN name)

### ISSUE THREAD

**Issue by flyingrub** [abarisain/dmix#688] opened 2015-01-22 14:40 UTC
In my mind in a fragment like the output one, we should have an option to add new output wich means (IP / Port / pass / ...) and the possibility to choose wich one we control right now with a single click.

**Comment by avuton** [comment] 2015-01-22 17:10
Duplicate of #374, not a trivial thing to implement, which is why it's not done yet.

**Closed by avuton** 2015-01-22 17:10 UTC
