### ISSUE TITLE
Show album art for streams that provide it

### ISSUE THREAD

**Issue by PanderMusubi** [abarisain/dmix#674] opened 2014-12-31 12:37 UTC
When playing streams that provide album art, the app should display this art. An example of such a stream is http://85.17.122.138:80/1 (Intergalactic FM - 1 Murdercapital FM)

This was reported against the latest version of 2014-12-09 with MPD version 0.16.7-2

**Comment by abarisain** [comment] 2015-01-04 15:12
Yeah, we tell MPD to read the m3u, and we don't know what it contains. Not sure we have the URL of the stream, but the phone would need to connect to the stream, read it, and then wait for the Metadata to come in, display the cover, etc ...  

It can probably be done, especially with the mediaMetadataRetriever just like @rejhgadellaa linked (I didn't know about it !), but it would require a rework of the Cover Art fetcher code, and many other aspects of MPDroid.  
I'd say that this feature is not requested enough for us to spend so much time on it, we've got other major stuff going on.

**Comment by avuton** [comment] 2015-11-03 02:22
Duplicate of #443.

**Closed by avuton** 2015-11-03 02:22 UTC
Labels: AlbumArt
