### ISSUE TITLE
album view:most various-artist-albums show as one; other gets split up

### ISSUE THREAD

**Issue by jmwatte** [abarisain/dmix#696] opened 2015-02-12 06:53 UTC
every one of my compilation albums show up in album view as 1 album. That's what I expect. Except this one which is a compilation of 1000 songs and it shows up as all these little albums grouped by every artist that is in there. I went through the tags of these albums but they look the same. Is this behaviour expected? And/or is there something I can do to make that album show up as 1 album instead of some 300 different albums?
Thx

**Comment by avuton** [comment] 2015-02-16 01:47
This is not my area of expertise, but this has something to do with the tags of that album. Might I suggest MusicBrainz Picard? Not saying this is not a bug in MPDroid.

**Comment by rripio** [comment] 2015-02-16 07:45
I have had this kind of problem only with albums in ape and wma format. It seems to be related with this mpd bug report: http://bugs.musicpd.org/view.php?id=4168

These albums were tagged with foobar2000.

**Comment by avuton** [comment] 2015-02-22 21:00
OK, for the sake of sanity, I'm going to close this bug. This is either a tagging problem or a MPD problem, either way, this is most likely not our issue. Feel free to reopen with more information about how this is a bug in the frontend.

**Closed by avuton** 2015-02-22 21:00 UTC
