### ISSUE TITLE
Add  everything to the current selection

### ISSUE THREAD

**Issue by Sigill** [abarisain/dmix#709] opened 2015-04-02 18:51 UTC
Sometimes, I just want to let my whole music library play randomly. But unless I missed it, there seems to be no way to send everything (every song from every album of every artist) to the current selection, it is only possible to do that from a selection (a genre, an artist, an album).

The only way I found to do this is to ssh to my mpc server and do a `mpc listall|mpc add`. Works well, but not very friendly.

**Comment by abarisain** [comment] 2015-04-02 18:52
I think that that may be quite a lot for mpdroid to fetch all the songs and send them back to the server, and really slow.

**Comment by avuton** [comment] 2015-04-02 19:01
Actually, the MPD protocol command `add /` works, but it's definitely a special case. If someone doesn't get to it first, I'll look at this some day.

**Comment by Sigill** [comment] 2015-04-02 19:14
I don't know how MPDroid sends items to the current selection, but even a few thousands song won't weight that much. I have nearly 5000 song in my media library, and the list of all filenames (returned by `mpc listall` "only" weight 425ko.

Thanks @avuton. The `add /` command indeed works, but it looks more like a hack than a feature.

**Comment by avuton** [comment] 2015-04-02 19:15
Not a hack at all, simply a documented part of the protocol.

**Comment by abarisain** [comment] 2015-04-02 19:41
425kb of data is quite a lot in the mobile world. And some people's library exceed the listall limit, which is why we will use `add /` once I figure out where to put it in the UI

**Comment by avuton** [comment] 2015-04-13 01:33
Closing as a duplicate of #199.

**Closed by avuton** 2015-04-13 01:33 UTC
Labels: JMPDComm, Wishlist
